select * from customer limit 20

-- 1.	What is the total revenue generated by male vs. female customers?

select gender, SUM(purchase_amount) as revenue 
from customer
group by gender

-- 2.	Which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

-- 3.	Which are the top 5 products with the highest average review rating?

-- round function doesn't work on double precision
select item_purchased, ROUND(AVG(review_rating::numeric), 2) as "Average Product Rating" -- round to 2 places
from customer
group by item_purchased
order by avg(review_rating) desc --descending order
limit 5 --top 5

-- 4.	Compare the average purchase amounts between standard and express shipping.

select shipping_type,
ROUND(AVG(purchase_amount), 2)
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type

-- 5.	Do subscribed customers spend more? Compare average spending and total revenue between subscribers and non-subscribers.

select subscription_status,
COUNT(customer_id) as total_customers, -- total number of customers sucscribed to the service
ROUND(AVG(purchase_amount), 2) as avg_spending,
ROUND(SUM(purchase_amount), 2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spending desc;

-- 6.	Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased, 
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*), 2) as discount_rate -- find the sum of all the times a discount was applied to a product
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- 7.	Segment customers into New, Returning, and Loyal based on their total number of previous purchases and show the count of each segment.

with customer_type as (
	select customer_id, previous_purchases,
	CASE 
		WHEN previous_purchases = 1 THEN 'New'
		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		ELSE 'Loyal'
		END AS customer_segment
from customer
)

-- count the number of customers falling into each segment
select customer_segment, COUNT(*) as "Number of Customers"
from customer_type
group by customer_segment

-- 8.	What are the top 3 most purchased products within each category?

with item_counts as (
	select category,
	item_purchased, COUNT(customer_id) as total_orders,
	ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
	from customer
	group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3; -- need the top 3 items

-- 9.	Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
-- customers with more than 5 purchases are considered frequent buyers

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

-- 10.	What is the revenue contribution of each age group

select age_group,
ROUND(SUM(purchase_amount), 2) as total_revenue
from customer
group by age_group
order by total_revenue desc;
